DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username  VARCHAR(250) NOT NULL,
    password VARCHAR(250) NOT NULL,
    first_name VARCHAR(250) DEFAULT NULL,
    last_name VARCHAR(250) DEFAULT NULL,
    email  VARCHAR(250) DEFAULT NULL
);